=== csaranyamca/csaranyamca/employeeschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<ey:schema xmlns:ey="http://www.w3.org/2001/XMLSchema">
    <ey:element name="Employee">
        <ey:complexType>
            <ey:sequence>
                <ey:element name="emp" maxOccurs="unbounded">
                    <ey:complexType>
                        <ey:sequence>
                            <ey:element name="emp-id" type="ey:string"></ey:element>
                            <ey:element name="name" type="ey:string"></ey:element>
                            <ey:element name="age" type="ey:integer"></ey:element>
                            <ey:element name="gender" type="ey:string"></ey:element>
                            <ey:element name="address" type="ey:string"></ey:element>
                            <ey:element name="emailid" type="ey:string"></ey:element>
                            <ey:element name="designation" type="desitype"></ey:element>
                            <ey:element name="specification" type="ey:string"></ey:element>
                            <ey:element name="yearofexperince" type="ey:string"></ey:element>
                            <ey:element name="salary" type="MySal"></ey:element>

                        </ey:sequence>
                    </ey:complexType>
                </ey:element>
            </ey:sequence>
        </ey:complexType>
    </ey:element>
    <ey:element name="designation" type="desitype" />

    <ey:simpleType name="desitype">
        <ey:restriction base="ey:string">
            <ey:enumeration value="Doctor" />
            <ey:enumeration value="Nurse" />
            <ey:enumeration value="Pharmacist" />
        </ey:restriction>
    </ey:simpleType>

    <ey:simpleType name="MySal">
        <ey:restriction base="ey:integer">
            <ey:minInclusive value="50000"></ey:minInclusive>
            <ey:maxInclusive value="350000"></ey:maxInclusive>
        </ey:restriction>
    </ey:simpleType>
</ey:schema>

=== csaranyamca/csaranyamca/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>
<Employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employeeschema.xsd">
    <emp>
        <emp-id>A1</emp-id>
        <name>Khasi</name>
        <age>56</age>
        <gender>M</gender>
        <address>Banglore</address>
        <emailid>Khasi20@gmail.com</emailid>
        <designation>Doctor</designation>
        <specification>Neuro</specification>
        <yearofexperince>30</yearofexperince>
        <salary>320000</salary>
    </emp>
    <emp>
        <emp-id>A2</emp-id>

        <name>Uma</name>
        <age>40</age>
        <gender>F</gender>
        <address>Banglore</address>
        <emailid>Uma20@gmail.com</emailid>
        <designation>Doctor</designation>
        <specification>Cardiology</specification>
        <yearofexperince>23</yearofexperince>
        <salary>250000</salary>
    </emp>
    <emp>
        <emp-id>A3</emp-id>
        <name>Suresh</name>
        <age>50</age>
        <gender>M</gender>
        <address>Banglore</address>
        <emailid>Suresh20@gmail.com</emailid>
        <designation>Doctor</designation>
        <specification>Ortho</specification>
        <yearofexperince>25</yearofexperince>
        <salary>250000</salary>
    </emp>
    <emp>
        <emp-id>A4</emp-id>

        <name>Geetha</name>
        <age>40</age>
        <gender>F</gender>
        <address>Banglore</address>
        <emailid>Geetha20@gmail.com</emailid>
        <designation>Nurse</designation>
        <specification>NULL</specification>
        <yearofexperince>20</yearofexperince>
        <salary>100000</salary>
    </emp>
    <emp>
        <emp-id>A5</emp-id>

        <name>George</name>
        <age>36</age>
        <gender>M</gender>
        <address>Banglore</address>
        <emailid>George20@gmail.com</emailid>
        <designation>Nurse</designation>
        <specification>NULL</specification>
        <yearofexperince>17</yearofexperince>
        <salary>80000</salary>
    </emp>
    <emp>
        <emp-id>A6</emp-id>

        <name>Kishore</name>
        <age>30</age>
        <gender>M</gender>
        <address>Banglore</address>
        <emailid>Kishore20@gmail.com</emailid>
        <designation>Pharmacist</designation>
        <specification>NULL</specification>
        <yearofexperince>10</yearofexperince>
        <salary>50000</salary>
    </emp>

</Employee>
